id: IE1EB52A9
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 17:58:07.937892+00:00
last_modified: 2022-12-14 17:58:07.937899+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-046-003
  eft-text-version: 1.1.4 2021
  title: Toh_97-The_Chapter_on_Manjusri%E2%80%99s_Magical_Display-v1
bases:
  F116:
    source_metadata: null
    order: 1
    base_file: F116.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
